development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: store_development
  pool: 5
  username: root
  password: "123456"
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: store_test
  pool: 5
  username: root
  password: "123456"
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: store_production
  pool: 5
  username: root
  password: "123456"
  host: localhost
